name: outputs

on: push

jobs:
  gen-outputs:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"

  use-outputs:
    needs: gen-outputs
    runs-on: ubuntu-latest
    steps:
        - run: echo "output1=${{ needs.gen-outputs.outputs.output1 }}"
        - run: echo "output2=${{ needs.gen-outputs.outputs.output2 }}"
