on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # This job requires the secrets FOO and BAR to be set using --secret flag from the CLI
      - name: Print Secret Values
        run: echo "${{ secrets.FOO }} = ${{ secrets.BAR }}"
