// Code generated by actions-generator. DO NOT EDIT.

package main

// Dagger module for executing the actions/hello-world-javascript-action GitHub Action.
type HelloWorldJavascriptAction struct{}

// Runs the actions/hello-world-javascript-action GitHub Action.
func (m HelloWorldJavascriptAction) Run(
	// Who to greet
	withWhoToGreet Optional[string],
	// Directory containing the repository source. Takes precedence over `--repo`.
	source Optional[*Directory],
	// Repository name, format: owner/name. Takes precedence over `--source`.
	repo Optional[string],
	// Tag name to check out. Only works with `--repo`. Takes precedence over `--branch`.
	tag Optional[string],
	// Branch name to check out. Only works with `--repo`.
	branch Optional[string],
	// Image for the runner.
	runnerImage Optional[string],
	// Enables debug mode.
	runnerDebug Optional[bool],
	// GitHub token. May be required for certain actions.
	token Optional[*Secret],
) *Container {
	// initializing runtime options
	opts := ActionsRuntimeRunOpts{
		Branch:      branch.GetOr(""),
		Repo:        repo.GetOr(""),
		RunnerDebug: runnerDebug.GetOr(false),
		RunnerImage: runnerImage.GetOr(""),
		Source:      source.GetOr(nil),
		Tag:         tag.GetOr(""),
		Token:       token.GetOr(nil),
	}

	return dag.ActionsRuntime().
		Run("actions/hello-world-javascript-action@main", opts).
		WithInput("who-to-greet", withWhoToGreet.GetOr("World")).
		Sync()
}
