on: push

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
          cache: false
          check-latest: false

      - run: go run . --help

