on:
  pull_request_target:
    types: [ opened, edited, reopened, synchronize ]

jobs:
  check-for-conventional-release-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
