on:
  pull_request_target:
    types: [ opened, reopened, synchronize, edited ]

permissions:
  issues: write
  pull-requests: write
  statuses: write
jobs:
  check-for-conventional-release-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
