on: [ pull_request ]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        workdir: [common, ghx]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          workdir: ${{ matrix.workdir }}
