on: [ pull_request ]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        workdir: [common, ghx]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          workdir: ${{ matrix.workdir }}

  daggerverse-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install Dagger CLI
        run: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }

      - name: Sync dagger modules
        run: dagger export -m ci daggerverse sync --output .

      - name: Check if daggerverse is up to date
        run: git diff --exit-code || (echo 'Uncommitted changes detected' && exit 1)

  gha-gen-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install Dagger CLI
        run: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }

      - name: Generate GitHub Actions modules
        run: dagger download -m ci gha generate -o gha/

      - name: Check if generated Github Actions modules is up to date
        run: git diff --exit-code || (echo 'Uncommitted changes detected' && exit 1)
