on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          package-name: gale
          pull-request-title-pattern: "build${scope}: release${component} ${version}"
          changelog-notes-type: github
