on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor  }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish docker image
        run: ./hack/mage docker:publish ${{ github.ref_name }}
